services:

  gobmap-service:
    image: gobmap-service
    container_name: gobmap
    build:
      context: services/gobmap-service
      dockerfile: Dockerfile
    ports:
      - ${GOBMAP_SERVICE_PORT}:8080
    environment:
      USER_DB: ${USERNAME_DB}
      PASSWORD_DB: ${PASSWORD_DB}
      NAME_DB: ${NAME_DB}
    networks:
      - gobmap-network
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${NAME_DB}
      POSTGRES_USER: ${USERNAME_DB}
      POSTGRES_PASSWORD: ${PASSWORD_DB}
    networks:
      - gobmap-network
    volumes:
      - gobmap-volume:/var/lib/postgres

volumes:
  gobmap-volume:
networks:
  gobmap-network: