services:

  gobmap-service:
    image: gobmap-service
    container_name: gobmap
    build:
      context: services/gobmap-service
      dockerfile: Dockerfile
    ports:
      - 8080:${GOBMAP_SERVICE_PORT}
    environment:
      USER_DB: ${USERNAME_DB}
      PASSWORD_DB: ${PASSWORD_DB}
      GOBMAP_SERVICE_PORT: ${GOBMAP_SERVICE_PORT}
      HOST_POSTGRES: ${HOST_POSTGRES}
    networks:
      - gobmap-network
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db_gobmap
      POSTGRES_USER: ${USERNAME_DB}
      POSTGRES_PASSWORD: ${PASSWORD_DB}
    networks:
      - gobmap-network
    volumes:
      - gobmap-volume:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  gobmap-volume:
networks:
  gobmap-network: