server:
  port: ${ACCESS_CONTROL_SERVICE_PORT}

spring:
  application:
    name: access-control

  r2dbc:
    url: r2dbc:postgresql://${HOST_POSTGRES}:5432/db_gobmap?currentSchema=sc_gobmap&ssl=false
    username: ${DB_USER}
    password: ${DB_PASSWORD}