server:
  port: ${GOBMAP_SERVICE_PORT}

spring:
  application:
    name: gobmap

  datasource:
    url: jdbc:postgresql://${HOST_POSTGRES}:5432/db_gobmap?currentSchema=sc_gobmap&ssl=false
    username: ${USER_DB}
    password: ${PASSWORD_DB}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
